language: node_js

node_js:
  - "8"

branches:
  only:
    - develop

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local_dir: dist
  on:
    branch: master

sudo: false
