# Site settings

title: Nelson Mfinda | Software Developer # put your blog title
description: Olá! sou Nelson Mfinda, desenvolvedor de software e freelancer, curioso, love open source, e estudante de Ciências da Computação # put your description for your amazing blog
baseurl: "" # the subpath of your site, e.g. /blog
canonical_url: "https://nelsonmfinda.me"
google_analytics: "UA-120927564-2"
permalink: /404
image: "assets/images/dunders.png"
url: "https://nelsonmfinda.me" # the base hostname & protocol for your site e.g. https://woliveiras.com.br
language: "pt-PT" # language to set into html tag, default is en
paginate: 5 # Number of posts on each page
paginate_path: "/page/:num" # links format for pagination
date_format: "%b %-d, %Y"  # dateformat of reading list, post date, and more
permalink: /:title/ # use to url friendly
timezone:  # timezone to show in yout sire
display-author-front-page: # True if you need show author name and site on home page
display-author-post-page: true # Very usual for guest posts and the infos of author are writen in header of post.md, by default show infos of user settings

# Useful for translating into other languages.

var_on_the_web: On the web
var_read: Continue...
var_newer: Newers
var_older: Olders
var_next_post: Next
var_previous_post: Previous
var_less_than_a_minute_read: < 1 min read
var_min_read: min read # Text after reading time. Example: 5 min read.
var_post_by: Writed by
var_guest_post_by: Guest post by
var_your_email: "info@nelsonmfinda.me"
var_your_message: Your message
var_page_indicator: Page
var_page_indicator_separator: of

# User settings

author: nelsonmfinda # put your name or a name of principal author of site/blog
email: hello@nelsonmfinda.me
twitter_username: nelsonmfinda
github_username:  nelsonmfinda
gplus_username:  nelsonmfinda
disqus_shortname: nelsonmfinda

# Navigation menu
links:
  - title: Nelson Mfinda | Software Developer
    url: /
  - title: About Me
    url: /about
  - title: My Skills
    url: /skills
  - title: Contact
    url: /contact
  - title: Projects
    url: /projects

# Build settings

markdown: kramdown
highlighter: rouge
sitemap: true # Generate sitemap.xml
feed:
  path: atom.xml
sass:
  sass_dir: _sass
  style: compressed
  
## For more settings: https://jekyllrb.com/docs/configuration/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - frasco.config.js
  - Gemfile
  - Gemfile.lock
  - gulp_tasks
  - gulpfile.js
  - LICENSE
  - node_modules
  - npm-debug.log
  - package.json
  - package-lock.json
  - README.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - yarn.lock